/* global BF2042Portal, _Blockly */
(function(){
'use strict';
const plugin=BF2042Portal.Plugins.getPlugin('Selection_List');
let lastBlock=null,lastId=null,observer=null;
function norm(v){return v==null?'':String(v).trim();}
function getBlock(){try{return _Blockly?.getMainWorkspace?.()?.getBlockById?.(String(lastId||''))||null}catch(_){return null}}
function safe(v){if(v===null||v===undefined)return v;if(typeof v==='function')return '[Function]';if(typeof v!=='object')return v;return undefined}
function ownSummary(obj){if(!obj||typeof obj!=='object')return null;const o={};for(const k of Object.keys(obj)){const v=safe(obj[k]);if(v!==undefined)o[k]=v;}return o}
function getDefinitions(){try{return BF2042Portal?.Startup?.getBlockDefinitions?.()}catch(_){return null}}
function toolboxInfo(){const ws=_Blockly?.getMainWorkspace?.();const tb=ws?.getToolbox?.();if(!tb)return null;function walk(items,path=[]){if(!Array.isArray(items))return [];const out=[];for(let i=0;i<items.length;i++){const it=items[i];if(!it)continue;let name='';try{name=norm(it.getName?.())||norm(it.name)||norm(it.label)||norm(it.categoryName)||norm(it.category)}catch(_){};const contents=(()=>{try{const x=it.getContents?.();if(Array.isArray(x))return x}catch(_){}for(const k of ['contents_','contents','blocks','items'])try{if(Array.isArray(it[k]))return it[k]}catch(_){}return []})();out.push({path:path.concat(i),name,type:it.constructor?.name||'',summary:ownSummary(it),contents:contents.map((c,j)=>({index:j,type:c?.type||'',kind:c?.kind||'',name:norm(c?.name)||norm(c?.label)||'',summary:ownSummary(c)}))});out.push(...walk(contents,path.concat(i)));}return out}const roots=tb.getToolboxItems?.()||tb.contents_||[];return walk(roots)}
function deepFindSelection(v,path=[],out=[],seen=new Set()){if(!v||typeof v!=='object'||seen.has(v)||out.length>500)return out;seen.add(v);if(Array.isArray(v)){v.forEach((x,i)=>deepFindSelection(x,path.concat(i),out,seen));return out}const text=Object.keys(v).join(' ')+' '+['name','label','category','categoryName','type','blockType','id'].map(k=>norm(v[k])).join(' ');if(/selection\s*list|選択リスト/i.test(text))out.push({path,summary:ownSummary(v)});for(const [k,c] of Object.entries(v)){if(k==='parent'||k==='workspace'||k==='svgRoot')continue;if(c&&typeof c==='object')deepFindSelection(c,path.concat(k),out,seen)}return out}
function download(){const b=lastBlock||getBlock();const defs=getDefinitions();const report={generated:new Date().toISOString(),selectedBlock:b?{id:b.id,type:b.type,fields:{}}:null,selectedBlockSummary:ownSummary(b),toolbox:toolboxInfo(),definitionsSelectionHits:deepFindSelection(defs),definitionsTypeMatches:[],notes:'Diagnostic only. This file is intended to reveal the actual PORTAL Selection Lists structure.'};if(b){for(const input of b.inputList||[])for(const f of input?.fieldRow||[]){let val='';try{val=norm(f.getValue?.())||norm(f.getText?.())}catch(_){}if(f?.name)report.selectedBlock.fields[f.name]=val}}
if(defs){const targetType=norm(b?.type);const seen=new Set();deepFindSelection(defs).forEach(()=>{});function walk(v,p=[],s=new Set()){if(!v||typeof v!=='object'||s.has(v))return;s.add(v);if(!Array.isArray(v)){const t=norm(v.type||v.blockType||v.kind||v.id);if(targetType&&t===targetType){const key=p.join('.');if(!seen.has(key)){seen.add(key);report.definitionsTypeMatches.push({path:p,summary:ownSummary(v)})}}for(const[k,c]of Object.entries(v)){if(k==='parent'||k==='workspace'||k==='svgRoot')continue;if(c&&typeof c==='object')walk(c,p.concat(k),s)}}else v.forEach((x,i)=>walk(x,p.concat(i),s))}walk(defs)}
const blob=new Blob([JSON.stringify(report,null,2)],{type:'text/plain;charset=utf-8'});const u=URL.createObjectURL(blob);const a=document.createElement('a');a.href=u;a.download='Selection_List_Diagnostic.txt';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function add(sub){if(!sub||sub.querySelector('[data-selection-list-debug]'))return;const d=document.createElement('div');d.className='bf6-options-menu-item';d.setAttribute('data-selection-list-debug','1');d.textContent='Selection List (Debug)';Object.assign(d.style,{padding:'5px 18px',whiteSpace:'nowrap',background:'rgb(22,29,30)',color:'#fff',cursor:'pointer',fontSize:'15px',lineHeight:'1.3',borderTop:'1px solid #3a4648',marginTop:'3px'});d.onclick=e=>{e.preventDefault();e.stopPropagation();download()};sub.appendChild(d)}
function scan(){document.querySelectorAll('.bf6-experience-manager-options-submenu').forEach(add)}
document.addEventListener('contextmenu',e=>{try{const el=e.target?.closest?.('g.blocklyDraggable');lastId=el?.getAttribute?.('data-id')||el?.dataset?.id||null;lastBlock=getBlock();setTimeout(scan,0)}catch(_){lastId=null;lastBlock=null}},true);
plugin.initializeWorkspace=async function(){if(!observer){observer=new MutationObserver(scan);observer.observe(document.documentElement||document.body,{childList:true,subtree:true})}scan()};
})();
